### ISSUE TITLE
setting locale

### ISSUE THREAD

**Issue by calderonsamuel** [gadenbuie/ggweekly#3]
I'm a spanish native speaker and I've been looking for a way to set locale inside `ggweek_planer()`.  This worked for me:

```r
library(ggweekly)

Sys.setlocale("LC_TIME", "es_PE.UTF8")

ggweek_planner(
  start_day = "2020-06-01", 
  end_day = "2020-07-31", 
  holidays = NULL
)
```
![image](https://user-images.githubusercontent.com/19418298/74752151-40638200-523c-11ea-8811-534a907fa941.png)

But I think it would be nice to be able to do it inside the call to `ggweek_planer()`

**Comment by gadenbuie** [comment]
Thanks for sharing! Honestly, I'm thrilled to hear that changing the locale correctly gives you a calendar with the right labels. I also think that this is probably the right approach unless there is some part of lubridate or ggweekly that _doesn't respect_ `Sys.getlocale("LC_TIME")`, in which case I'd need to address that.

**Comment by calderonsamuel** [comment]
I think I just found one in line 118 of ggweekly.R

This doesn't work when the locale is changed:
```r
weekend   = .data$wday_name %in% c("Sat", "Sun")
```

I think something like this would work, but I am not sure this is the best way to do it:
```r
weekend   = .data$wday_name %in% lubridate::wday(as.Date(2:3, origin = "1970-01-01"), 
                                                 label = TRUE)
```
